package examen.Final;

public class AreaCuadrado /*extends Area */{
	
	//FINAL EN UNA CLASE

	//EN ESTE CASO VEMOS QUE LA CLASE AREA NO PUEDE SER HEREDADA
	//YA LA YA MENCIONADA CLASE "AREA" A SIDO DECLARADA COMO "final"
	//ESTO SIGNIFICA QUE LA CLASE NO PUEDE SER HEREDADA. COMO SE PUEDE
	//OBSERVAR EN LA LINEA 3, SI INTENTA HEREDAR LA CLASE AREA
	//NO SE PUEDE COMPILAR EL CODIGO
	
	//ESTO EVIDENTEMENTE NO ES ALGO QUE SE DEBERIA HACER, YA QUE 
	//DEBERIAMOS USAR LA CLASE AREA PARA USARLA DIRECTAMENTE EN LA
	//CALCULADORA Y ASI HACER QUE EL CODIGO SEA MÁS FLEXIBLE Y COMPACTO,
	//LO IDEAL SERÍA DECLARAR A LA CLASE "Area" COMO "abstract".

	//RESUMIENDO, EL "final" EN UNA CLASE EVITA QUE SE PUEDA HEREDAR.
	
	double areaCuadrado(double l) {
		double a = l * l;
		return a;
	}
	
	
}
